### ISSUE TITLE
Wrong alias for youtube video

### ISSUE THREAD

**Issue by dftossem** [quocvu/hexo-tag-youtube-responsive#1]
There is an extra 'r' in the example command in README.md
Error:
{% youtuber video 0pjcieqhm3A %}
Fix:
{% youtube video 0pjcieqhm3A %}

**Comment by quocvu** [comment]
Thanks for reaching out.  I am confirming it is indeed `youtuber`.  There is already a `youtube` tag to embed a YouTube video, but it is not responsive.
