### ISSUE TITLE
including just `{% youtuber %}` will throw error if not including `{% endyoutuber %}`

### ISSUE THREAD

**Issue by car-meows** [quocvu/hexo-tag-youtube-responsive#2]
following error will be thrown if `{% endyoutuber %}` is not included: <img width="1130" alt="Screenshot 2020-03-09 at 10 46 08 AM" src="https://user-images.githubusercontent.com/15316889/76178707-402f2480-61f3-11ea-9ac5-f46bd278a359.png">

**Comment by lunhg** [comment]
Same here

**Comment by quocvu** [comment]
Thanks for the report. I have updated the documentation to always include the closing tag.  Unfortunately, Hexo does not allow to make the closing tag optional.
